### ISSUE TITLE
All scylla nodes down during single az control plane upgrade

### ISSUE THREAD

**Issue by etix** [scylladb/scylla-operator#458] opened 2021-03-02 16:31 UTC
**Describe the bug**
When deploying Scylla on a single AZ (i.e. only a single master) upgrading the Kubernetes master makes all Scylla nodes restart.

**To Reproduce**
1. Deploy a single az Kubernetes cluster (with a version < latest)
2. Deploy Scylla (tested using the helm chart) and wait for the cluster to be up and running.
3. Upgrade the Kubernetes control-plane to the latest version
4. As soon as the control plane is up, you can see the whole Scylla cluster down and restarting

**Expected behavior**
Scylla pods should not restart while the control plane is being upgraded.

**Logs**
I failed to get useful logs of the event since the control plane was down. 

**Environment:**
 - Platform:  GKE
 - Kubernetes version: v1.17.17-gke.1101
 - Scylla version: 4.2.3
 - Scylla-operator version: nightly

**Additional context**
Pods restart without clean shutdown causing log replays on reboot and since all the nodes are down simultaneously the whole cluster is looking for a valid seed and wait for minutes with the message "Connect seeds again" before going back up.

**Comment by tnozicka** [comment] 2021-03-03 07:24
> Nodes should not restart while the control plane is being upgraded.
Kube update usually means upgrading kubelet on nodes and OS with reboot which drains nodes. For HA setup we are working on adding PDB so only 1 member can be evicted (at a time) when nodes are being drained.

Can you be more specific about your deployment? Was it single node or HA cluster? Schedulable masters?

>I failed to get useful logs of the event since the control plane was down.
Although this doesn't sound like HA setup. Were there other nodes?

**Comment by etix** [comment] 2021-03-03 09:07
> Kube update usually means upgrading kubelet on nodes and OS with reboot which drains nodes.

The update process on GKE is:
1. Upgrade the master
2. Upgrade the node pools

The issue happened during the master upgrade. All services continued to run except Scylla. I can't tell for sure if Scylla pods went down during the upgrade or right after the master came back up. But I believe it was down the entire process because I reconnected quickly after the master was available again and the pods were restarted uncleanly: the replay log was being replayed and it took a while.

> For HA setup we are working on adding PDB so only 1 member can be evicted (at a time) when nodes are being drained.

I have manually added a PDB to Scylla on this cluster already. The PDB helped during node upgrades, no problem there. The nodes upgrade happened as expected (thanks to the PDB).

> Can you be more specific about your deployment? Was it single node or HA cluster? Schedulable masters?

It's single AZ Kubernetes cluster in `us-central1-c` that is our staging cluster. Our production cluster, which is a regional one (with multiple master) is not affected by this issue. The Scylla cluster has 3 nodes and this is how it is deployed:

```yaml
cpuset: false # if the node has four or fewer CPUs, don’t use this option.
hostNetworking: true
developerMode: false

sysctls:
- "fs.aio-max-nr=2097152"

scyllaImage:
  repository: scylladb/scylla
  # Overrides the image tag whose default is the chart appVersion.
  tag: 4.2.3 # 4.3.0 bug: https://github.com/scylladb/scylla/issues/8032

backups:
- name: "daily backup"
  location: ["gcs:scylla-backups"]
  interval: "1d"
  retention: 31
  keyspace: ["*", "!jaeger_v1"]
repairs:
- name: "repair"
  interval: "2d"
  intensity: "2"
  keyspace: ["*", "!jaeger_v1"]

datacenter: us-central1
racks:
- name: us-central1-c
  members: 3
  storage:
    capacity: 40G
  resources:
    limits:
      cpu: 1
      memory: 5G
    requests:
      cpu: 1
      memory: 5G
  placement:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            # for 1.17+ : topology.kubernetes.io/zone
            - key: failure-domain.beta.kubernetes.io/zone
              operator: In
              values:
              - us-central1-c
    tolerations:
      - key: role
        operator: Equal
        value: scylla-clusters
        effect: NoSchedule
  agentVolumeMounts:
    - name: scylla-manager-service-account
      mountPath: /var/run/secret/scylla/
      readOnly: true
  volumes:
    - name: scylla-manager-service-account
      secret:
        secretName: scylla-manager-service-account

# Whether to create Prometheus ServiceMonitor
serviceMonitor:
  create: true
```

**Comment by etix** [comment] 2021-03-03 09:15
My personal assumption is that a service either in Scylla or Scylla-operator is misbehaving when the master is unreachable or has been unreachable for a while and forces a restart.

**Comment by tnozicka** [comment] 2021-03-03 10:34
thanks for the info, we'll try to reproduce and see what happens; could be a livenessProbe or something that restart while master api down

**Comment by tnozicka** [comment] 2021-03-03 14:27
I haven't get to trying it yet but while working on something else I've noticed sidecar liveness probe leading to https://github.com/scylladb/scylla-operator/blob/629e325/pkg/controllers/sidecar/identity/member.go#L37 which talks to kube api to get the members. Few options to solve it if it prove to be this:
- use just the local endpoint
- informers/listers (we shouldn't waste live calls there anyways)

**Comment by etix** [comment] 2021-03-03 15:46
Indeed, it could totally be the sidecar's fault. Maybe the readiness and liveness probes are still partially active while the control-plane is unresponsive (on the API side) causing a restart of the pods because the sidecar is trying to list members from the control-plane before answering successfully to the probe requests.

The general idea is that if the k8s master is unresponsive, all applications should wait for the control-plane to come back (+ maybe some slight delay for it to catch up) before taking any decision. In our case, the liveness/readiness probes should probably return "success" if the member list cannot be retrieved. Anyway, no cluster-wide operation can be done while there's no control-plane available.

**Comment by tnozicka** [comment] 2021-03-03 17:15
Yep, if our liveness probe fails just because kube api is down, we are doing it wrong. Generally injecting the sidecar into scylla image is not great either because it couples the sidecar lifecycle to scylla itself. After chatting with @zimnx we will get rid of this sidecar and migrate most of the code into the operator. If needed we can extract some parts or it into a separate container to separate the lifecycle.

**Comment by yanniszark** [comment] 2021-03-03 17:38
> extract some parts or it into a separate container to separate the lifecycle

Note that (AFAIK) there is no way to upgrade a Pod's container without recreating/restarting the whole Pod. Thus, the lifecycle stills seems to be coupled. I would love to be proved wrong on this one though :)

**Comment by tnozicka** [comment] 2021-03-04 09:23
I meant it as if a separate sidecar container fails it restarts independently and doesn't bring down scylla process which is running fine.

> Note that (AFAIK) there is no way to upgrade a Pod's container without recreating/restarting the whole Pod. 

@yanniszark Can you elaborate on what you mean here? Like what the difference would be or where you see the change challenging?

**Comment by tnozicka** [comment] 2021-12-02 12:59
the sidecar now uses informers, i think this should be fixed

**Closed by tnozicka** 2021-12-02 12:59 UTC
Labels: kind/bug
