### ISSUE TITLE
Mgmt backup fails with `create task: start date of scheduled task cannot be in the past` when it is 12+ backup in a row

### ISSUE THREAD

**Issue by vponomaryov** [scylladb/scylla-operator#1683] opened 2024-01-11 17:38 UTC
### What happened?

Running the `scylla-manager backup` nemesis in the loop multiple times.
Everything was good first 11 backups.
But starting with the 12th one we get following error:
```
E0111 15:14:17.108750       1 manager/sync.go:137] "Failed to execute action" err="[POST /cluster/{cluster_id}/tasks][500] PostClusterClusterIDTasks default  &{Message:create task: start date of scheduled task cannot be in the past TraceID:yl4Vnpl8Sj6WvLM_Mql2_Q}" action="add task &{ClusterID: Enabled:true ID: Name:default-backup-task-name-11 Properties:map[location:[s3:manager-backup-tests-us-east-1] retention:3] Schedule:0xc000a5c1e0 Tags:[] Type:backup}"
{"L":"INFO","T":"2024-01-11T15:14:17.108Z","N":"backup","M":"Done checking accessibility of remote locations","_trace_id":"yl4Vnpl8Sj6WvLM_Mql2_Q"}
{"L":"INFO","T":"2024-01-11T15:14:17.108Z","N":"scheduler","M":"PutTask","task":"backup/66499e00-5000-4d83-ac79-8f1f6b0fbbd0","schedule":{"cron":"","window":null,"timezone":"","start_date":"2024-01-11T15:14:11.888Z","interval":"","num_retries":3,"retry_wait":""},"properties":{"location":["s3:manager-backup-tests-us-east-1"],"retention":3},"create":true,"_trace_id":"yl4Vnpl8Sj6WvLM_Mql2_Q"}
{"L":"INFO","T":"2024-01-11T15:14:17.108Z","N":"http","M":"POST /api/v1/cluster/307ae3e2-2298-469a-bf65-1003c9201655/tasks","from":"10.0.9.40:44750","status":500,"bytes":127,"duration":"2995ms","error":"create task: start date of scheduled task cannot be in the past","_trace_id":"yl4Vnpl8Sj6WvLM_Mql2_Q"}
I0111 15:14:17.121293       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="scylla/sct-cluster" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"sct-cluster\": the object has been modified; please apply your changes to the latest version and try again"
```

Probably related to the following:
- https://github.com/scylladb/scylla-operator/issues/838

### What did you expect to happen?

I expected the `mgmt backup` operation work always.

### How can we reproduce it (as minimally and precisely as possible)?

- Deploy scylla-operator (latest)
- Deploy scylla-manager (3.2.5)
- Deploy 3-node Scylla cluster
- Run `scylla-manager` backup operation in a loop

### Scylla Operator version

`v1.12.0-alpha.0-144-g60f7824` (`latest`)

### Kubernetes platform name and version

`EKS , K8S v1.27.3`

## Installation details

Kernel Version: 5.10.201-191.748.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.3-20231219.b890271f125b` with build-id `26667e5fe9023e6f688ca3bab2ee5f910abfd2cb`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.12.0-alpha.0-144-g60f7824
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 3 nodes (i4i.4xlarge)

OS / Image: `` (k8s-eks: `eu-north-1`)

Test: `vp-longevity-scylla-operator-3h-eks-backup`
Test id: `d2a96761-d796-4558-b07a-c4e726fdf472`
Test name: `scylla-staging/valerii/vp-longevity-scylla-operator-3h-eks-backup`
Test config file(s):

- [longevity-scylla-operator-3h-backup.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/eb6ca5db8b017be0c911b81c4a2101f578bf1978/test-cases/scylla-operator/longevity-scylla-operator-3h-backup.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor d2a96761-d796-4558-b07a-c4e726fdf472`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d2a96761-d796-4558-b07a-c4e726fdf472)
- Show all stored logs command: `$ hydra investigate show-logs d2a96761-d796-4558-b07a-c4e726fdf472`

## Logs:
- **kubernetes-d2a96761.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/kubernetes-d2a96761.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/kubernetes-d2a96761.tar.gz)
- **kubernetes-must-gather-d2a96761.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/kubernetes-must-gather-d2a96761.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/kubernetes-must-gather-d2a96761.tar.gz)
- **db-cluster-d2a96761.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/db-cluster-d2a96761.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/db-cluster-d2a96761.tar.gz)
- **sct-runner-events-d2a96761.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/sct-runner-events-d2a96761.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/sct-runner-events-d2a96761.tar.gz)
- **sct-d2a96761.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/sct-d2a96761.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/sct-d2a96761.log.tar.gz)
- **loader-set-d2a96761.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/loader-set-d2a96761.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/loader-set-d2a96761.tar.gz)
- **monitor-set-d2a96761.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/monitor-set-d2a96761.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d2a96761-d796-4558-b07a-c4e726fdf472/20240111_162047/monitor-set-d2a96761.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/valerii/job/vp-longevity-scylla-operator-3h-eks-backup/8/)
[Argus](https://argus.scylladb.com/test/bbfc12c7-0991-4148-88d2-88e131326a93/runs?additionalRuns[]=d2a96761-d796-4558-b07a-c4e726fdf472)

**Comment by rzetelskik** [comment] 2024-01-26 11:41
```
E0111 15:14:17.108750       1 manager/sync.go:137] "Failed to execute action" err="[POST /cluster/{cluster_id}/tasks][500] PostClusterClusterIDTasks default  &{Message:create task: start date of scheduled task cannot be in the past TraceID:yl4Vnpl8Sj6WvLM_Mql2_Q}" action="add task &{ClusterID: Enabled:true ID: Name:default-backup-task-name-11 Properties:map[location:[s3:manager-backup-tests-us-east-1] retention:3] Schedule:0xc000a5c1e0 Tags:[] Type:backup}"
{"L":"INFO","T":"2024-01-11T15:14:17.108Z","N":"backup","M":"Done checking accessibility of remote locations","_trace_id":"yl4Vnpl8Sj6WvLM_Mql2_Q"}
{"L":"INFO","T":"2024-01-11T15:14:17.108Z","N":"scheduler","M":"PutTask","task":"backup/66499e00-5000-4d83-ac79-8f1f6b0fbbd0","schedule":{"cron":"","window":null,"timezone":"","start_date":"2024-01-11T15:14:11.888Z","interval":"","num_retries":3,"retry_wait":""},"properties":{"location":["s3:manager-backup-tests-us-east-1"],"retention":3},"create":true,"_trace_id":"yl4Vnpl8Sj6WvLM_Mql2_Q"}
{"L":"INFO","T":"2024-01-11T15:14:17.108Z","N":"http","M":"POST /api/v1/cluster/307ae3e2-2298-469a-bf65-1003c9201655/tasks","from":"10.0.9.40:44750","status":500,"bytes":127,"duration":"2995ms","error":"create task: start date of scheduled task cannot be in the past","_trace_id":"yl4Vnpl8Sj6WvLM_Mql2_Q"}
I0111 15:14:17.121293       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="scylla/sct-cluster" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"sct-cluster\": the object has been modified; please apply your changes to the latest version and try again"
```

@vponomaryov where are these logs coming from? I can't find anything from the manager controller in the operator logs.

```
$ cat kubernetes-must-gather-d2a96761/longevity-scylla-operator-3h-dev-d2a96761/must-gather/namespaces/scylla-operator/pods/scylla-operator-568c697964-hlrbs/scylla-operator.current | grep "manager/sync\|manager/controller" | wc -l
0
```

I think I know the reason, but I'd like to see these logs anyway.

**Comment by vponomaryov** [comment] 2024-01-26 11:50
> ```
> E0111 15:14:17.108750       1 manager/sync.go:137] "Failed to execute action" err="[POST /cluster/{cluster_id}/tasks][500] PostClusterClusterIDTasks default  &{Message:create task: start date of scheduled task cannot be in the past TraceID:yl4Vnpl8Sj6WvLM_Mql2_Q}" action="add task &{ClusterID: Enabled:true ID: Name:default-backup-task-name-11 Properties:map[location:[s3:manager-backup-tests-us-east-1] retention:3] Schedule:0xc000a5c1e0 Tags:[] Type:backup}"
> {"L":"INFO","T":"2024-01-11T15:14:17.108Z","N":"backup","M":"Done checking accessibility of remote locations","_trace_id":"yl4Vnpl8Sj6WvLM_Mql2_Q"}
> {"L":"INFO","T":"2024-01-11T15:14:17.108Z","N":"scheduler","M":"PutTask","task":"backup/66499e00-5000-4d83-ac79-8f1f6b0fbbd0","schedule":{"cron":"","window":null,"timezone":"","start_date":"2024-01-11T15:14:11.888Z","interval":"","num_retries":3,"retry_wait":""},"properties":{"location":["s3:manager-backup-tests-us-east-1"],"retention":3},"create":true,"_trace_id":"yl4Vnpl8Sj6WvLM_Mql2_Q"}
> {"L":"INFO","T":"2024-01-11T15:14:17.108Z","N":"http","M":"POST /api/v1/cluster/307ae3e2-2298-469a-bf65-1003c9201655/tasks","from":"10.0.9.40:44750","status":500,"bytes":127,"duration":"2995ms","error":"create task: start date of scheduled task cannot be in the past","_trace_id":"yl4Vnpl8Sj6WvLM_Mql2_Q"}
> I0111 15:14:17.121293       1 manager/controller.go:148] "Hit conflict, will retry in a bit" Key="scylla/sct-cluster" Error="Operation cannot be fulfilled on scyllaclusters.scylla.scylladb.com \"sct-cluster\": the object has been modified; please apply your changes to the latest version and try again"
> ```
> 
> @vponomaryov where are these logs coming from? I can't find anything from the manager controller in the operator logs.
> 
> ```
> $ cat kubernetes-must-gather-d2a96761/longevity-scylla-operator-3h-dev-d2a96761/must-gather/namespaces/scylla-operator/pods/scylla-operator-568c697964-hlrbs/scylla-operator.current | grep "manager/sync\|manager/controller" | wc -l
> 0
> ```
> 
> I think I know the reason, but I'd like to see these logs anyway.

Use non-`must-gather` `kubernetes` logs.
It has streamed data from the `scylla-manager`.
The logs from the bug description were taken from there.

**Comment by rzetelskik** [comment] 2024-01-26 12:05
My bad, I forgot the manager controller has a separate deployment, so I was looking in the wrong place.

**Comment by rzetelskik** [comment] 2024-01-26 13:20
I believe this is generally caused by https://github.com/scylladb/scylla-operator/issues/1705. Operator currently adds 30s to the timestamp taken at sync. The tasks are scheduled serially, so it looks like with that many tasks added at once, the time to sync goes over the buffer.

https://github.com/scylladb/scylla-operator/pull/1706 should resolve it in this particular case, but changing the start date to "now+duration" will fail sooner or later, depending on the duration and latency. I logged a separate issue for this https://github.com/scylladb/scylla-operator/issues/1708, and a couple of somewhat related issues with scylla manager: 

The fact that we schedule the tasks serially is no less concerning to me than the broken syntax. This particular test suggests that the reconciliation took over 30s, as the backup scheduling started failing despite the "safety buffer". I'll have to run a similar test locally with debug logs to confirm that the reconciliation takes this long.

**Comment by vponomaryov** [comment] 2024-01-26 13:45
> ... so it looks like with that many tasks added at once, the time to sync goes over the buffer.

Just clarifying that all the tasks that were created in the test run used for the bug report were created serially after completion of a previous one.

**Comment by rzetelskik** [comment] 2024-01-26 14:31
> So, statement many tasks added at once is not correct referring to the situation in the bug report.

Thanks, I assumed they were scheduled at once. Anyway I'll have to try and reproduce it.

**Comment by rzetelskik** [comment] 2024-05-16 14:27
Fixed in https://github.com/scylladb/scylla-operator/pull/1706 and https://github.com/scylladb/scylla-manager/commit/c9ee2e6af6dd04ec46766ebe3f33a83750d809d8.

**Closed by rzetelskik** 2024-05-16 14:27 UTC
Labels: kind/bug, priority/important-soon
