### ISSUE TITLE
[Flake] Scylla Manager integration [It] should register cluster and sync repair tasks

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla-operator#1900] opened 2024-04-18 14:16 UTC
### Link to the job that flaked.

https://prow.scylla-operator.scylladb.com/view/gs/scylla-operator-prow/pr-logs/pull/scylladb_scylla-operator/1855/pull-scylla-operator-master-e2e-gke-parallel-clusterip/1780919077133357056#1:test-build-log.txt%3A1192

Seems like the repair task wasn't deleted.

### Snippet of what failed.
```
   [FAILED] Unexpected error:
      <wait.errInterrupted>: 
      timed out waiting for the condition
      {
          cause: <*errors.errorString | 0xc0005cab80>{
              s: "timed out waiting for the condition",
          },
      }
  occurred
  In [It] at: github.com/scylladb/scylla-operator/test/e2e/set/scyllacluster/scyllamanager.go:211 @ 04/18/24 11:53:03.805 
```

**Comment by rzetelskik** [comment] 2024-04-18 16:11
Duplicate of https://github.com/scylladb/scylla-operator/issues/1694

**Closed by rzetelskik** 2024-04-18 16:11 UTC
Labels: priority/important-soon, kind/flake
