### ISSUE TITLE
readyness probe fails

### ISSUE THREAD

**Issue by dangersorus** [scylladb/scylla-operator#388] opened 2021-02-16 02:48 UTC
Just tried to do a helm install, get readyness probe failure on basic helm install.

**Comment by zimnx** [comment] 2021-02-16 16:22
It's because recent helm chart use new readness probes available in master builds. Make sure to try latest chart with latest Operator version.

**Comment by eljoth** [comment] 2021-02-18 06:19
Duplicate of https://github.com/scylladb/scylla-operator/issues/354

**Closed** 2021-02-23 09:55 UTC
Labels: bug
