### ISSUE TITLE
Ephemeral Storage  capacity change - Forbidden

### ISSUE THREAD

**Issue by brickpattern** [scylladb/scylla-operator#1517] opened 2023-11-01 00:33 UTC
Environment:
AWS EKS : latest 
Scylla Operator : v1.11 
Setup: 5 node cluster  ( 1:1 scylla node to EKS node) with XFS storage on the NVME disk on the instance. 
Storage type : ephemeral
Issue: underlying EKS node  instance has enough storage . Attempt to increase the storage capacity  in scylla.yaml  resulted in below error. 

>  spec.datacenter.racks[0].storage: Forbidden: changes in storage are currently not supported

**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Increase the storage of the scylla node as permitted by the underlying ephemeral storage.  When a cluster is operational with data,  setting a capacity attribute  be honored if the underlying ephemeral storage has enough volume to accomodate.

**What is use case behind this feature:**
If this is not supported, how else do we increase or replace the scylla nodes maximizing the storage capacity? 

**Additional Information:**

**Comment by tnozicka** [comment] 2023-11-01 07:23
This issue is inherited from Kubernetes StatefulSets (see https://github.com/kubernetes/kubernetes/issues/68737) the workaround is suggested in https://github.com/scylladb/scylla-operator/issues/825

Closing as dupe of https://github.com/scylladb/scylla-operator/issues/1103

**Closed by tnozicka** 2023-11-01 07:23 UTC
Labels: needs-priority

**Comment by tainnsre** [comment] 2024-10-17 04:15
I was changed this values in the chart scylla but when I install it then it is error
  helm git:(main) ✗ helm upgrade --install scylla scylla/scylla --create-namespace --namespace scylla --values ./scylla/values.yaml --debug

history.go:56: [debug] getting history for release scylla
upgrade.go:158: [debug] preparing upgrade for scylla
upgrade.go:166: [debug] performing update for scylla
upgrade.go:364: [debug] creating upgraded release for scylla
client.go:393: [debug] checking 1 resources for changes
client.go:693: [debug] Patch ScyllaCluster "scylladb-cluster" in namespace scylla
W1017 11:13:53.501955   44447 warnings.go:70] unknown field "spec.datacenter.racks[0].resources.placement"
W1017 11:13:53.501986   44447 warnings.go:70] unknown field "spec.datacenter.racks[1].resources.placement"
W1017 11:13:53.501992   44447 warnings.go:70] unknown field "spec.datacenter.racks[2].resources.placement"
client.go:425: [debug] error updating the resource "scylladb-cluster":
	 cannot patch "scylladb-cluster" with kind ScyllaCluster: admission webhook "webhook.scylla.scylladb.com" denied the request: ScyllaCluster.scylla.scylladb.com "scylladb-cluster" is invalid: [spec.datacenter.racks[0].storage: Forbidden: changes in storage are currently not supported, spec.datacenter.racks[1].storage: Forbidden: changes in storage are currently not supported, spec.datacenter.racks[2].storage: Forbidden: changes in storage are currently not supported]
upgrade.go:476: [debug] warning: Upgrade "scylla" failed: cannot patch "scylladb-cluster" with kind ScyllaCluster: admission webhook "webhook.scylla.scylladb.com" denied the request: ScyllaCluster.scylla.scylladb.com "scylladb-cluster" is invalid: [spec.datacenter.racks[0].storage: Forbidden: changes in storage are currently not supported, spec.datacenter.racks[1].storage: Forbidden: changes in storage are currently not supported, spec.datacenter.racks[2].storage: Forbidden: changes in storage are currently not supported]
Error: UPGRADE FAILED: cannot patch "scylladb-cluster" with kind ScyllaCluster: admission webhook "webhook.scylla.scylladb.com" denied the request: ScyllaCluster.scylla.scylladb.com "scylladb-cluster" is invalid: [spec.datacenter.racks[0].storage: Forbidden: changes in storage are currently not supported, spec.datacenter.racks[1].storage: Forbidden: changes in storage are currently not supported, spec.datacenter.racks[2].storage: Forbidden: changes in storage are currently not supported]
helm.go:84: [debug] cannot patch "scylladb-cluster" with kind ScyllaCluster: admission webhook "webhook.scylla.scylladb.com" denied the request: ScyllaCluster.scylla.scylladb.com "scylladb-cluster" is invalid: [spec.datacenter.racks[0].storage: Forbidden: changes in storage are currently not supported, spec.datacenter.racks[1].storage: Forbidden: changes in storage are currently not supported, spec.datacenter.racks[2].storage: Forbidden: changes in storage are currently not supported]
helm.sh/helm/v3/pkg/kube.(*Client).Update
	helm.sh/helm/v3/pkg/kube/client.go:438
helm.sh/helm/v3/pkg/action.(*Upgrade).releasingUpgrade
	helm.sh/helm/v3/pkg/action/upgrade.go:418
runtime.goexit
	runtime/asm_arm64.s:1222
UPGRADE FAILED
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:240
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_arm64.s:1222
