### ISSUE TITLE
[ScyllaOperator helm version 1.11.1] CQL: fetch TLS config: get SSL user cert from secrets store: not found

### ISSUE THREAD

**Issue by firegrouptech** [scylladb/scylla-operator#1704] opened 2024-01-26 06:41 UTC
Hello everyone,

I encountered an issue after installing the Scylla Operator 1.11.1 chart version. I used the default values for both scylla-operator and scylla-manager. For ScyllaDB, I configured the following settings:

```
developerMode: true
cpuset: false
hostNetworking: true
automaticOrphanedNodeCleanup: true
datacenter: "k3s"
# List of racks
racks:
  - name: "local"
    # Name of additional scylla config configMap
    scyllaConfig: "scylla-config"
    # Name of additional scylla manager agent config stored as secret
    scyllaAgentConfig: "scylla-agent-config"
    # Number of rack members (nodes)
    members: 3
    # Storage definition
    storage:
      capacity: 10Gi
    # Scylla container resource definition
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
```
The deployment was successful. However, when I executed the command sctool status -c scylla/scylla inside the scylla-manager pod, I encountered an error, as shown in the image below.
![image](https://github.com/scylladb/scylladb/assets/156646587/c3ecb584-7565-428e-bf35-92f74ec6433a)
Is it a normal error ? 
Does it have any effect?
If effect, how can i fix it ?
Is there any way to disable TLS Config and use it without TLS

**Resolved:**
- I have resolved this issue by editing command setting "AutomaticTLSCertificates=false"

![image](https://github.com/scylladb/scylla-operator/assets/156646587/198e4196-6b33-4cb7-9ef9-8ec91ae59669)
![image](https://github.com/scylladb/scylla-operator/assets/156646587/8d81e701-4611-45fa-829b-a7ac1421ba94)
CQL is up after disabled TLS
is there any way to disable it via the value helm file ?

**Comment by tnozicka** [comment] 2024-01-26 07:27
dupe of https://github.com/scylladb/scylla-operator/issues/1674

**Closed by tnozicka** 2024-01-26 07:27 UTC
Labels: needs-priority

**Comment by firegrouptech** [comment] 2024-01-26 07:40
> dupe of #1674

![image](https://github.com/scylladb/scylla-operator/assets/156646587/e7f7bbad-e77f-4594-88f1-860e9be09ead)
I use scyllaArgs: "--feature-gates=AutomaticTLSCertificates=false" on the helm value
But it did not work ?

**Comment by tnozicka** [comment] 2024-01-26 08:39
> But why did it not work ?

I can't tell - you didn't follow the bug template and a must-gather is missing... Please provide the must-gather archive if you wish to receive further assistance.
/shrug

**Comment by zimnx** [comment] 2024-01-26 08:54
`scyllaArgs` controls parameters to ScyllaDB, not Scylla Operator. 
We don't have a way to control feature gates via Helm.
