### ISSUE TITLE
syslog audit is not logged in logs

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-operator#1299] opened 2023-07-21 17:08 UTC
When Scylla audit is configured to use syslog then audit logs are not forwarded to pod log and user is unable to use this feature.

**Comment by tnozicka** [comment] 2023-07-24 11:21
> When Scylla audit is configured to use syslog then audit logs are not forwarded to pod log

Well, if you tell it to log somewhere else then pod logs (stdout / journald) I'd not be surprised it's not returning it in pod logs.

**Comment by tnozicka** [comment] 2023-07-24 11:26
@tzach would we be fine with auditing to a table only? that seems to be already present and sylogs would need extra infra and multitenancy code - I don't yet see the value for syslog compared to the table.

**Comment by fruch** [comment] 2023-07-25 07:15
> @tzach would we be fine with auditing to a table only? that seems to be already present and sylogs would need extra infra and multitenancy code - I don't yet see the value for syslog compared to the table.

we found audit to table is broken, and can affect user queries, for now syslog option is consider as the suggested way.

regardless, this issue probably need to be moving to scylla-core, and we need the docker image be able to show the audit regardless of operator.

cloud would probably gonna work on some why a user could get his own audit, and then we'll need to see how operator fits in (if at all)

**Comment by mykaul** [comment] 2023-07-25 13:34
We should close this issue and open an issue 'support external (syslog?) audit logging'. I don't think we'd like to have yet another mechanism, other than syslog and we certainly don't want to use the table.

**Comment by ptrsmrn** [comment] 2023-07-25 20:39
Seems like @soyacz found a solution and syslog appears to work correctly (https://github.com/scylladb/scylla-cluster-tests/pull/6328#issuecomment-1649224077), is that correct? If so, perhaps we can close this issue.

**Comment by soyacz** [comment] 2023-07-26 07:12
> Seems like @soyacz found a solution and syslog appears to work correctly ([scylladb/scylla-cluster-tests#6328 (comment)](https://github.com/scylladb/scylla-cluster-tests/pull/6328#issuecomment-1649224077)), is that correct? If so, perhaps we can close this issue.

this is for VM based tests and I found this issue when trying to test with k8s.

**Comment by tnozicka** [comment] 2023-07-26 08:35
Is the table broken by design?

I am not sure whether syslog is the way to go or not. Doesn't seem multitenant so I guess you'd somehow have to setup dedicated collectors at which point the value of having it is a bit lower. In the end it's not about Kubernetes itself that much - wonder how'd see the audit log collected if there were 3 VMs each running N scylla nodes with different user ids that can't log to the same syslog or use the same collector I suppose.

In general setting syslog collector per scyllacluster is a lot of work, nodes have to expose the port, something needs to setup syslog server, setup authentication and expose it to users, collect node endpoints, propagate mTLS certificates, ... - whereas using a table needs no infra or setup.

**Comment by mykaul** [comment] 2023-07-26 09:50
> Is the table broken by design?

It's not amazing (see https://github.com/scylladb/scylla-enterprise/issues/2939 for example) and it's not very useful being accessible via CQL.

> 
> I am not sure whether syslog is the way to go or not. Doesn't seem multitenant so I guess you'd somehow have to setup dedicated collectors at which point the value of having it is a bit lower. In the end it's not about Kubernetes itself that much - wonder how'd see the audit log collected if there were 3 VMs each running N scylla nodes with different user ids that can't log to the same syslog or use the same collector I suppose.
> 
> In general setting syslog collector per scyllacluster is a lot of work, nodes have to expose the port, something needs to setup syslog server, setup authentication and expose it to users, collect node endpoints, propagate mTLS certificates, ... - whereas using a table needs no infra or setup.

Then we need to figure out an alternative. I think in VMs we'd move with Vector to push logs elsewhere.

**Comment by ptrsmrn** [comment] 2023-07-26 09:52
> Is the table broken by design?

Yes, it seems so. Current schema results in big and/or hot partitions and other issues (see e.g. https://github.com/scylladb/scylla-enterprise/issues/2939 or generally enterprise issues with `audit` label: https://github.com/scylladb/scylla-enterprise/issues?q=is%3Aopen+is%3Aissue+label%3Asecurity%2FAudit).

> I am not sure whether syslog is the way to go or not. Doesn't seem multitenant so I guess you'd somehow have to setup dedicated collectors at which point the value of having it is a bit lower. In the end it's not about Kubernetes itself that much - wonder how'd see the audit log collected if there were 3 VMs each running N scylla nodes with different user ids that can't log to the same syslog or use the same collector I suppose.

Current design of audit table can kill a cluster (if a node with audit partition goes down, no audited operations can be performed, because they cannot be logged into audit table) or decrease its availability. The idea is to switch table to the local replication strategy, which would mean the same problem as for syslog, i.e. we'd need to provide tooling to gather audit logs from all the nodes.  

> In general setting syslog collector per scyllacluster is a lot of work, nodes have to expose the port, something needs to setup syslog server, setup authentication and expose it to users, collect node endpoints, propagate mTLS certificates, ... - whereas using a table needs no infra or setup.

I agree, but if we won't be able to fix audit table, we have to switch to syslog, which is very likely atm.

**Comment by soyacz** [comment] 2023-07-26 16:50
> In general setting syslog collector per scyllacluster is a lot of work, nodes have to expose the port, something needs to setup syslog server, setup authentication and expose it to users, collect node endpoints, propagate mTLS certificates, ... - whereas using a table needs no infra or setup.

Isn't it just another rule in rsyslog configuration in Scylla's pod to redirect it to the pod log?
Anyway user of Scylla in k8s should have have a means to read pod logs, so could use the same to read audit log too.

**Comment by tnozicka** [comment] 2023-07-28 14:13
> Isn't it just another rule in rsyslog configuration in Scylla's pod to redirect it to the pod log?

I don't see how mixing audit and regular logs could be practical. Something would need to parse it out later on and I don't think all the logs we write are structured. The retention policies / scale for each of them are usually different as well.

That said, if we can make it log to a different file, we could expose it like any other logs with [streaming sidecar container](kubernetes.io/docs/concepts/cluster-administration/logging/#streaming-sidecar-container). Although not best in terms of controlling log rotation policies or making guarantees about whether an external agent (like datadog) has scrapped it.

I guess we can allow configuring remote rsyslog but audit usually blocks queries and there may be availability issues. Running local one as well will bring a lot of multitenancy challenges, that may take time to figure out.

**Closed** 2024-08-21 10:41 UTC
Labels: kind/bug, lifecycle/rotten
