### ISSUE TITLE
Support vertical scaling of nodes

### ISSUE THREAD

**Issue by ghenom** [scylladb/scylla-operator#186] opened 2020-09-19 01:55 UTC
Currently it is only possible to add members to the cluster.
It would be nice to be able to change the requests/limits as seen fit including the disk size ( increasing ).
Based on the scylla cluster conf:
  datacenter:
    name: us-central1
    racks:
    - members: 1
      name: us-central1-f
      resources:
        limits:
          cpu: 4
          memory: 16Gi
        requests:
          cpu: 4
          memory: 16Gi
      scyllaAgentConfig: scylla-agent-config
      scyllaConfig: scylla-config
      storage:
        capacity: 1000Gi
        storageClassName: ssd-storage

**Comment by zimnx** [comment] 2020-09-21 07:36
Duplicate of #112

**Closed by zimnx** 2020-09-21 07:36 UTC
Labels: enhancement
