### ISSUE TITLE
Enable to add command line options that are used to start scylla

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-operator#192] opened 2020-10-01 11:03 UTC
* Feature Request

**What should the feature do:**
User should be able to add command line options to what is used to start scylla on the nodes

**What is use case behind this feature:**
There are list of options that are available only via command line, user can have a need to pass them to the container
Also QA team uses them in certain tests

**Comment by zimnx** [comment] 2020-10-01 12:09
Duplicate of #177

**Closed by zimnx** 2020-10-01 12:09 UTC
Labels: enhancement
