### ISSUE TITLE
Wrong IP used when replacing a node second time

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla-operator#1439] opened 2023-10-02 11:40 UTC
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

In functional tests first we run test `test_drain_kubernetes_node_then_replace_scylla_node` and then we run similar one `test_drain_kubernetes_node_then_wait_and_replace_scylla_node`. It happened that the same k8s node was chosen for drain and test failed because Scylla node couldn't boot after replace due to error:
```
ERROR 2023-10-01 05:02:41,050 [shard  0] init - Startup failed: std::runtime_error (Cannot replace_address 172.20.237.141 because it doesn't exist in gossip)
```
This happens, because `172.20.237.141` was already replaced in previous test. So operator uses wrong IP address for replacement.

to reproduce, try drain K8s node and replace Scylla node - twice.
## Impact

New node doesn't start

## How frequently does it reproduce?

First time seen - don't know if the same k8s node chosen for drain was used before (random)

## Installation details

Kernel Version: 5.10.192-183.736.amzn2.x86_64
Scylla version (or git commit hash): `2023.1.0~rc8-20230731.b6f7c5a6910c` with build-id `f6e718548e76ccf3564ed2387b6582ba8d37793c`

Operator Image: scylladb/scylla-operator:latest
Operator Helm Version: v1.11.0-alpha.0-114-g8ac0a21
Operator Helm Repository: https://storage.googleapis.com/scylla-operator-charts/latest
Cluster size: 4 nodes (i4i.4xlarge)

Scylla Nodes used in this run:
**No resources left at the end of the run**

OS / Image: `` (k8s-eks: undefined_region)

Test: `functional-eks`
Test id: `040a6c7d-9a4d-4ae5-826b-46801962ae58`
Test name: `scylla-operator/operator-master/functional/functional-eks`
Test config file(s):

- [functional.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/fa73cde2127567560e3cf64260f55b3275a86a24/test-cases/scylla-operator/functional.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 040a6c7d-9a4d-4ae5-826b-46801962ae58`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=040a6c7d-9a4d-4ae5-826b-46801962ae58)
- Show all stored logs command: `$ hydra investigate show-logs 040a6c7d-9a4d-4ae5-826b-46801962ae58`

## Logs:
- **kubernetes-040a6c7d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/kubernetes-040a6c7d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/kubernetes-040a6c7d.tar.gz)
- **db-cluster-040a6c7d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/db-cluster-040a6c7d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/db-cluster-040a6c7d.tar.gz)
- **sct-runner-events-040a6c7d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/sct-runner-events-040a6c7d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/sct-runner-events-040a6c7d.tar.gz)
- **sct-040a6c7d.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/sct-040a6c7d.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/sct-040a6c7d.log.tar.gz)
- **loader-set-040a6c7d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/loader-set-040a6c7d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/loader-set-040a6c7d.tar.gz)
- **parallel-timelines-report-040a6c7d.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/parallel-timelines-report-040a6c7d.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/040a6c7d-9a4d-4ae5-826b-46801962ae58/20231001_051117/parallel-timelines-report-040a6c7d.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-operator/job/operator-master/job/functional/job/functional-eks/120/)
[Argus](https://argus.scylladb.com/test/89fdaa2f-5255-4696-a268-90cb7090482e/runs?additionalRuns[]=040a6c7d-9a4d-4ae5-826b-46801962ae58)
</details>

**Comment by zimnx** [comment] 2023-10-02 12:05
Does issue reproduce when ScyllaDB version is `2023.1.0` (not `rc8`)? I think it should fixed in new procedure, used when ScyllaDB version is high enough.

**Comment by soyacz** [comment] 2023-10-03 05:44
I don't know yet, I switched our jobs to run with 2023.1.1

**Comment by tnozicka** [comment] 2023-10-16 07:23
We think it was fixed in the aforementioned version. Please reopen this if you see this on the version requested.

**Comment by fruch** [comment] 2023-10-16 07:24
I can confirm that we didn't seen this issue in the last two week, since moving to test with 2023.1.1

**Closed by tnozicka** 2023-10-16 07:23 UTC
Labels: kind/bug, priority/important-soon
