### ISSUE TITLE
Support changes in resources

### ISSUE THREAD

**Issue by vladiceanu** [scylladb/scylla-operator#112] opened 2020-06-02 12:25 UTC
**Is this a bug report or feature request?**
* Feature Request

**What should the feature do:**
Enable users to scale up the cluster resources (cpu, memory, disk) through the _scylla-operator_.

**What is use case behind this feature:**
When trying to increase a resource (i.e. memory) in the operator configuration, we're getting the following error message:
```sh
 admission webhook "validating-create-update-cluster.scylladb.com" denied the request: rack eu-west-1b: changes in resources are not currently supported
```

**Additional Information:**
We were able to "patch" the `StatefulSet` and increase the memory (in the _scylla-operator_ the values are still the old), the Pods got updated and showing the new memory values, but will Scylla actually use all the memory that the Pod has or limit to the values from `datacenter.racks.resources`?

**Comment by dahankzter** [comment] 2020-06-02 12:58
How did you patch it?  an you show the command? Did the pods restart automatically on the patch or did you restart them? What resource did you change?

Patching memory and then restarting should be safe as long as you are sure there is enough memory available. 

It's a little bit intriguing though. I thought this would be forbidden by Kubernetes itself as well.

**Comment by vladiceanu** [comment] 2020-06-02 13:05
> How did you patch it? an you show the command? Did the pods restart automatically on the patch or did you restart them? What resource did you change?
I just used `kubectl edit sts <sts-name>`, then increased the **memory** value. The Pods got restarted one-by-one automatically with the new memory value. 

The operator didn't overwrite the new value and neither complain when redeployed the pipeline.

**Comment by forsberg** [comment] 2020-09-02 13:40
Memory and CPU changes to statefulset has not been a problem as long as I've been using Kubernetes (version 1.6 and up if I remember correctly). There used to be trouble patching size of volumes, but that has also been fixed. I know of other operators that support it (The Strimzi Kafka operator for example), which are also using statefulset.

As noted above, Kubernetes will simply restart the pods automatically using the podManagementPolicy, ensuring each pod reports readiness before continuing with the next.

**Comment by forsberg** [comment] 2020-09-08 06:33
When it comes to disk, it's worth taking inspiration from Strimzi Kafka Operator, where the amount of disk is defined in the Kafka CRD. The operator will notice changes, modify the PVCs, wait for them to be resized fully, *then* restart the pods. Very convenient.

**Comment by mmatczuk** [comment] 2020-09-08 07:49
That's indeed neat if you plan for multi tenancy, otherwise with Scylla it's better to have 1-1 kubenetes node to scylla node mapping.

**Comment by forsberg** [comment] 2020-09-08 11:48
I know Scylla has been designed and optimized to be as close to the hardware as possible, and that it thrives best when it gets to eat the whole cake.

However, there are also use cases where the full performance you get from using a whole node is not needed, be it development clusters, or simply workloads which are not (yet) using up a whole node. In that case it's highly useful to be able to run Scylla on the same node as other workloads, using Kubernetes. Once the workload increases to a level where it uses a whole node, I'll allocate a full node, and that's one of the places where it becomes very convenient to be able to adjust CPU and memory resources of a running cluster.

Same thing with disk. I know Scylla recommends using machines with local SSD attached, but not all use cases need this kind of performance, and being able to gradually grow by using e.g. EBS SSD on AWS, increasing its size as the data fills up, is also useful.

**Comment by gnumoreno** [comment] 2020-09-22 15:01
Some other things to take into consideration:

1. Adding more cpus to scylla will trigger resharding.
2. We should strive to keep a good cpu:ram:storage ratio.
3. /usr/lib/scylla/scylla_io_setup should run after disk changes.

**Comment by ezbz** [comment] 2021-02-23 09:13
Duplicate of #402

**Closed by ezbz** 2021-02-23 09:13 UTC
Labels: enhancement
